### ISSUE TITLE
Option for minimizing on start

### ISSUE THREAD

**Issue by nikitashhh** [macdems/yet-another-spotify-tray#3]
Hey, first of all thanks for your great app, because it's really amazing.
Could you please add option for minimizing on start, because when we want to start a Spotify client from a apps menu, for example, we don't really want it to be minimized. So could you please add option for that, something like "-m" or "--minimized" would be great.
I have tried to do that by myself, but I haven't found where the app is being minimized on its boot.
Thanks in advance.

**Comment by nikitashhh** [comment]
**Update:** I have done the feature that I described in this issue, but I believe that I haven't done it in the best way it can be done, because I have never worked with Qt Framework, so I haven't opened a PR. There's is my [solution (very bad)](https://github.com/sccoouut/yet-another-spotify-tray/tree/no_startup_hide). If you want I can open a PR, or if you can find a better way to implement it, it would be very nice. Again, thanks in advance.

**Comment by taffarel55** [comment]
I had this need and what I did was add a script to start when the computer turns on. This script kills spotify (for some reason I couldn't remove it from startup :smile: ), starts it again, after a sleep starts the spotify-tray. I can share it here, I just don't do it now because I did it on my personal computer and it's dead now.

**Comment by macdems** [comment]
Thank you for your comments. I prefer to keep the minimized startup a default, so I have added a `--show-window` command line option. It must be specified as the first argument as all the others are passed to Spotify.

Also in your script you does not have to kill Spotify. `spotify-tray` will capture existing Spotify window instead of starting a new instance.
